/** @type {import('tailwindcss').Config} */
export default {
    content: [
        "./index.html",
        "./src/**/*.{js,ts,jsx,tsx}",
    ],
    darkMode: "class",
    theme: {
        extend: {
            colors: {
                "on-surface": "#ffffff",
                "surface-container": "#1a1a1a",
                "outline": "#767575",
                "on-secondary-fixed": "#510085",
                "primary": "#ff9159",
                "on-tertiary-fixed": "#372400",
                "on-secondary": "#340058",
                "on-primary": "#531e00",
                "surface": "#0e0e0e",
                "on-primary-container": "#401500",
                "on-tertiary": "#5e4000",
                "primary-fixed-dim": "#f66700",
                "tertiary": "#ffc562",
                "secondary-dim": "#c57eff",
                "tertiary-container": "#fbb423",
                "error-container": "#b92902",
                "tertiary-fixed-dim": "#eba60f",
                "surface-bright": "#2c2c2c",
                "secondary-fixed": "#e7c5ff",
                "primary-dim": "#ff7524",
                "surface-variant": "#262626",
                "primary-fixed": "#ff7a2f",
                "surface-container-low": "#131313",
                "on-surface-variant": "#adaaaa",
                "on-tertiary-fixed-variant": "#5e4000",
                "tertiary-fixed": "#fbb423",
                "background": "#0e0e0e",
                "on-error-container": "#ffd2c8",
                "on-background": "#ffffff",
                "secondary": "#c57eff",
                "outline-variant": "#484847",
                "surface-container-highest": "#262626",
                "inverse-surface": "#fcf9f8",
                "surface-container-high": "#20201f",
                "secondary-container": "#6a0baa",
                "inverse-on-surface": "#565555",
                "on-error": "#450900",
                "on-primary-fixed": "#000000",
                "tertiary-dim": "#eba60f",
                "surface-dim": "#0e0e0e",
                "on-secondary-container": "#e6c3ff",
                "surface-tint": "#ff9159",
                "on-primary-fixed-variant": "#4f1c00"
            },
            fontFamily: {
                "headline": ["Space Grotesk", "sans-serif"],
                "body": ["Inter", "sans-serif"],
                "label": ["Inter", "sans-serif"],
                "mono": ["JetBrains Mono", "monospace"]
            },
            borderRadius: {
                "DEFAULT": "0.125rem",
                "lg": "0.25rem",
                "xl": "0.5rem",
                "full": "0.75rem"
            },
        },
    },
    plugins: [],
}
